services:
  web:
    build:
      context: ./front
      dockerfile: Dockerfile
    container_name: pulse-front
    ports:
      - "3000:3000"
      - "24678:24678"
    volumes:
      - ./front:/app
    tty: true
    stdin_open: true
